# Generated by Django 3.2 on 2021-04-17 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Package', max_length=50)),
                ('status', models.CharField(choices=[('O', 'Open'), ('T', 'In transit'), ('IS', 'In stock'), ('OS', 'On issue')], default='O', max_length=4)),
                ('time_arrived', models.DateTimeField(default=datetime.datetime(2021, 4, 17, 20, 18, 31, 624653))),
                ('time_of_departure', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 20, 18, 31, 624653))),
            ],
        ),
    ]
