# Generated by Django 3.2 on 2021-04-17 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='position',
            field=models.CharField(blank=True, choices=[('P1', 'Position №1'), ('P2', 'Position №2'), ('P3', 'Position №3'), ('P4', 'Position №4')], max_length=4),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 20, 22, 5, 602766)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 20, 22, 5, 602766)),
        ),
    ]
