# Generated by Django 3.2 on 2021-04-17 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20210417_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(default='Position', max_length=50),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('L', 'on load'), ('OC', 'occupied')], default='OP', max_length=4),
        ),
        migrations.AddField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 21, 25, 8, 553055)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 21, 25, 8, 553055)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 17, 21, 25, 8, 553055)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 21, 25, 8, 554055)),
        ),
    ]
