# Generated by Django 3.2 on 2021-04-20 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_auto_20210420_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 50, 54, 713348)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 10, 50, 54, 713388)),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 50, 54, 712425)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 50, 54, 714628)),
        ),
    ]
