# Generated by Django 3.2 on 2021-04-21 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_auto_20210420_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 12, 18, 54, 467902)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 12, 18, 54, 467938)),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 12, 18, 54, 466662)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='status',
            field=models.CharField(choices=[('A', 'Await package'), ('M', 'Moving'), ('IS', 'In stock'), ('OB', 'On base')], default='A', max_length=4),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 12, 18, 54, 468847)),
        ),
    ]
