# Generated by Django 3.2 on 2021-04-21 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_auto_20210421_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 13, 9, 42, 601138)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 21, 13, 9, 42, 601181)),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('L', 'On load'), ('OC', 'Occupied')], default='OP', max_length=4),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 13, 9, 42, 599906)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 13, 9, 42, 602019)),
        ),
    ]
