# Generated by Django 3.2 on 2021-04-22 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_auto_20210421_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('T', 'In transit'), ('IS', 'In stock'), ('OS', 'On issue'), ('G', 'Is gone')], default='O', max_length=4),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 16, 56, 43, 900698)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 16, 56, 43, 900712)),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 16, 56, 43, 900382)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 16, 56, 43, 901015)),
        ),
    ]
