# Generated by Django 3.2 on 2021-04-22 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_auto_20210422_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 18, 29, 16, 908333)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 18, 29, 16, 908346)),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_number',
            field=models.CharField(choices=[('1', 'Position #1'), ('2', 'Position #2'), ('3', 'Position #3'), ('4', 'Position #4'), ('5', 'Position #5')], default='1', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 18, 29, 16, 908016)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 18, 29, 16, 908652)),
        ),
    ]
