# Generated by Django 3.2 on 2021-04-22 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_auto_20210422_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 18, 29, 22, 68138)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 22, 18, 29, 22, 68151)),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 18, 29, 22, 67820)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 18, 29, 22, 68461)),
        ),
    ]
