# Generated by Django 3.2 on 2021-05-10 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_auto_20210423_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Command', max_length=50)),
                ('status', models.CharField(choices=[('A', 'Appointed'), ('P', 'Performed'), ('F', 'Finished')], default='A', max_length=4)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 5, 10, 17, 25, 16, 332913))),
                ('time_exec', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 17, 25, 16, 332926))),
                ('time_finish', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 17, 25, 16, 332936))),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='time_arrived',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 17, 25, 16, 332268)),
        ),
        migrations.AlterField(
            model_name='package',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 17, 25, 16, 332281), null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='time_info_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 17, 25, 16, 331940)),
        ),
        migrations.AlterField(
            model_name='robotstatus',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 17, 25, 16, 332656)),
        ),
    ]
